baseline = {
    'k_net_income': 30750.0,
    'r_net_income': 7500.0,
    'k_crop_yield': 0.5,
    'r_crop_yield': 1.4,
    'k_crc': 1.0,
    'r_crc': 1.2,
    'no_hh': 48032,
    'no_cattle_perhh': 2,
    'profit_per_cattle': 10000,
    'wr_cattle_day': 80,
    'fr_cattle_day': 50,
    'fraction_residue_fodder': 1,
    'fraction_produce_fodder': 0.3,
    'mass_manure_per_cattle_per_year': 0.4,
    'k_cwr_mm': 600,
    'r_cwr_mm': 450,
    'soil_density': 1400,
    'height_topsoil': 0.3,
    'perc_OM_target': 2,
    'perc_OM_depleted': 1,
    'total_water_available': 0,
}

scenario1 = {
    'k_net_income': 0,
    'r_net_income': 0,
    'k_crop_yield': 0,
    'r_crop_yield': 0,
    'k_crc': 0,
    'r_crc': 0,
    'no_hh': 0,
    'no_cattle_perhh': 0,
    'profit_per_cattle': 0,
    'wr_cattle_day': 0,
    'fr_cattle_day': 0,
    'fraction_residue_fodder': 0,
    'fraction_produce_fodder': 0,
    'mass_manure_per_cattle_per_year': 0,
    'k_cwr_mm': 0,
    'r_cwr_mm': 0,
    'soil_density': 0,
    'height_topsoil': 0,
    'perc_OM_target': 0,
    'perc_OM_depleted': 0,
    'total_water_available': 0,
}